services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Web app
      - "587:587"    # SMTP
    environment:
      - PORT=3000    # Internal for Next.js compilation
    volumes:
      - ./data:/app/data
      - ./certificates:/app/certificates
    restart: unless-stopped
